### PR TITLE
READ.ME and SEEG update

### PR DESCRIPTION
**Pull request by VictorHugoTerziani**
Updating the READ.ME file with the badges from Shield.Io
Inserting the following badges:
- Languages being used
- Commits 
- Open Issues
- Closed Issues
- Files
- Followers
with the intention to show more of Datazoom's activity.

Updating the SEEG file to alert users that the function load_seeg will ask for API permissions of google drive.

### CODE REVIEW

**Review by IgorRigolon — CHANGES_REQUESTED** [review]
Looks very good, only two comments:

1. The README.Rmd file must be "knit" to generate a README.md file that is actually visible on the github repo.

2. SEEG is not the only function that uses `googledrive` and thus has these same issues, so I'd actually request that, instead of adding this new text to SEEG, you should create a new vignette called "googledrive" that I can later insert into the readme. This way, all the functions that use `googledrive` can get a disclaimer at the bottom, something like 

``` 
"This function uses the `googledrive` package to download data. In case of authentication errors, see [link to the "googledrive" vignette]". 
```

**Comment by AntonioBergallo** [comment]
Good morning! Made some changes in the README and added some warning messages in the functions that load datasets which require "googledrive" package. Unfortunately, did not check the conversation before writing those, so my message is a little bit different.

**Comment by AntonioBergallo** [comment]
Just saw that all the checks have failed. Not sure exactly what happened. No error messages, only one warning in each software.

**Comment by IgorRigolon** [comment]
@AntonioBergallo it's because the new messages you added to iema, imazon, and seeg contain some illegal (non-ascii) character, not sure which. 

Either way, in the cran_preparation branch I have added a message straight from download.R: whenever the `googledrive` package is used the message is sent, without having to manually add the messages to each function. I'm just waiting for a final check before merging that PR.

**Comment by AntonioBergallo** [comment]
@IgorRigolon just realized that. I think it is the ":". Thanks for the help! Should I delete the messages then?

**Comment by AntonioBergallo** [comment]
@IgorRigolon it was probably that. Thanks for the help. Totally forgot about the function "check". Going to update and run it on my computer. Should I delete the "googledrive" messages, as you have already padronized them on download.R?

**Comment by IgorRigolon** [comment]
> @IgorRigolon it was probably that. Thanks for the help. Totally forgot about the function "check". Going to update and run it on my computer. Should I delete the "googledrive" messages, as you have already padronized them on download.R?

Yeah I guess. It was a good initiative by you though, it's my fault that the new things haven't been merged yet.

**Comment by AntonioBergallo** [comment]
> > @IgorRigolon it was probably that. Thanks for the help. Totally forgot about the function "check". Going to update and run it on my computer. Should I delete the "googledrive" messages, as you have already padronized them on download.R?
> 
> @AntonioBergallo Yeah I guess. It was a good initiative by you though, it's my fault that the new things haven't been merged yet.

@IgorRigolon No problem! Thanks for the help anyway. As you are already here, could you give me some feedback on the README updates?

**Pull request merged**
